### ISSUE TITLE
Would node gene and connection gene deletions created disconnected graphs?

### ISSUE THREAD

**Issue by jasonzliang** [CodeReclaimers/neat-python#10]
I took a look at the mutate_delete_node() and mutate_delete_connection() methods in genome.py and noticed there seems to be no checks for whether the deletion will separate the network into two unconnected components. This might be serious issue if the deletion separates the input and output layers of the network.

**Comment by CodeReclaimers** [comment]
Thanks for mentioning this!  You are correct--there is nothing preventing disconnected networks from being created.  I haven't added any checks for this kind of network because I didn't want to create default behavior that could potentially interfere with evolution of a solution. 

While I don't have a solid theoretical justification for why one must allow a disconnected network, I have an anecdote: I've seen disconnected networks persistently turn out to be the most-fit genome during early evolution of a recurrent car-driving network.  Whether that is just a fluke, or a bug/idiosyncratic behavior in either neat-python or the TORCS simulator, I don't know, but if not, it seems they could be a useful stepping-stone to building a more fit, connected, network.

Even if the disconnected networks always perform more poorly than any connected network, presumably any species which produce disconnected genomes would rapidly die out and be replaced by those more likely to produce connected networks.  The current neuron/network implementations shouldn't experience any difficulties evaluating a disconnected network, but if you do have an instance in which they raise exceptions, please let me know.

If it turns out that you have problems in which a disconnected network is a big problem, one simple solution is to add a check for this condition in your fitness function, and if the network is disconnected, assign it a very low score and return.  

If there is a class of problems that require this kind of check, please reopen this item and let me know, and I can make the library configurable so that it will do the check for you without having to write any extra code.
