### ISSUE TITLE
Pip install not up to date

### ISSUE THREAD

**Issue by thecog19** [CodeReclaimers/neat-python#103]
A friend and I have discovered an alarming behavior, where running the exact same code, but having installed neat from pip vs from github, gives differing behaviors. I tested this with my friend @HiggstonRainbird and we decided it merited opening an issue. To replicate, you can clone the following repo: [https://github.com/thecog19/neat-bug-demo](https://github.com/thecog19/neat-bug-demo )

On a computer running linux, having installed neat .91 with pip install, run

``` python evolve-feedforward_fizzbuzz.py ```

The network will never reach an answer, choosing to, instead, de-evolve every few hundred iterations, as so: [http://i.imgur.com/mBMoQKr.png](http://i.imgur.com/mBMoQKr.png)

When instead neat is installed via the github repo, the network will solve the problem within 2000 generations, usually closer to 1000. 

This is obviously undesirable behavior, and it caused us many headaches, so we thought we'd share.

**Comment by d0pa** [comment]
I am on a phone, usually I just download from git hub directly, since you already have both sources. Can you please compare  sources against each other. My guess pip install version is behind in commits.

_Sent from my Samsung SM-G950U using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by drallensmith** [comment]
Well, we're currently working on a new release - see #102 - that includes the `DefaultStagnation` code changes that should help with this, judging from a glance at the screenshot. It should be going out to pip as version 0.92 (current available via pip is version 0.91). [@d0pa: It would be nice if there were. a pip-available version - neat-python-dev or neat-python-latest or something - that did automatically keep up with github commits... I've seen systems like that before.]

**Comment by CodeReclaimers** [comment]
Thanks for the report @thecog19! Unfortunately updates to pip have languished a bit this year because I've been short on free time, but some other folks have stepped in to pick up the slack. :)  As @drallensmith says, we should have a new release really soon.

I like the idea of having a neat-python-dev or neat-python-nightly package if we find that there are lots of forthcoming improvements that change rapidly but still take a while to hash out.

**Comment by CodeReclaimers** [comment]
I just pushed release 0.92 to PyPI, so please give that a spin and make sure things work as you expect.

**Comment by d0pa** [comment]
@drallensmith do you mean have bash/python script that would automatically publish on pypi any new commits ? So after setup and new commit users can run "pip install neat-python-latest" ?

**Comment by drallensmith** [comment]
That would be one possibility; will have to investigate how other projects do it.

**Comment by d0pa** [comment]
It looks simple, I setup pypi account and test repo. 
This how setup looks like so far:
1. Pool via GitHub API commits events (I am looking at rest API to figure out limits and best event to pool)
2. If new commit then publish via [pypi script](http://peterdowns.com/posts/first-time-with-pypi.html)
3. Send Notification ?

**Comment by d0pa** [comment]
Looks like this is a good [solution ](https://developer.github.com/v3/repos/commits/)to check for commit updates,
