### ISSUE TITLE
What does the picture2d example do?

### ISSUE THREAD

**Issue by jjmontesl** [CodeReclaimers/neat-python#11]
I can run the picture2d example, but I cannot understand what it does or how I should use it... could you please provide a little explanation?

**Comment by CodeReclaimers** [comment]
Sure thing--left-click on the images you want to reproduce for the next generation, and then close the window.  (When you left-click on an image it toggles selection, selected images are outlined in red.) NEAT will create the next generation, open a new window and display them.  The genomes that you select will be written to file so that you can load and use them later if you wish.

I need to clean it up and make it a bit more obvious what's going on.  I'll include this explanation in a README file while I'm at it.  Hopefully I'll have time to do that soon.

**Comment by CodeReclaimers** [comment]
I pushed the most recent version of the picture2d example, and added a README file in that directory.  Please let me know if you have any other troubles with it!
