### ISSUE TITLE
How-to. Save and load a network

### ISSUE THREAD

**Issue by cliftonarms** [CodeReclaimers/neat-python#113]
Not strictly an issue : I have looked through the documentations and examples and cannot find how to save/load a trained network. Please help anyone.

Thanks in advance.

**Comment by d0pa** [comment]
Look at [checkpoint.py](https://github.com/CodeReclaimers/neat-python/blob/master/neat/checkpoint.py) how pickle is used to save/load generation. You can use pickle in same way to store your trained network.

**Comment by drallensmith** [comment]
Another example, for one network at a time, is in
examples/picture2d/evolve_interactive.py.

-Allen

**Comment by mdalvi** [comment]
I think this query **should be marked as resolved** since the answers provide enough information on the question. Alternatively, you can always search for `pickle.dump` or `pickle.load` in all example files via something like **`'Find in all files' of Notepad++`** to point yourself to respective code.
