### ISSUE TITLE
'xor2_config' is missing

### ISSUE THREAD

**Issue by duijnhouwer** [CodeReclaimers/neat-python#13]
example file XOR2 on documentation wiki can't run without this config file.

**Comment by CodeReclaimers** [comment]
Thanks, I can see how that would be confusing.  I'll put a note on the documentation page about that, and give a link to the config file so people don't have to chase it down.

**Comment by duijnhouwer** [comment]
hi, thanks,

actually, i think my neat-python is out of date

i installed it using

pip install neat-python from PyPI

I'm using Python 3.4, Windows 10, Visual Studio 2015

Could it be that an old version is on PyPI?

How do I get the most up to date version from you GitHub to work on my
computer?

I'm new to python from Matlab and C/C++, sorry if these questions are
overly noobious...

Thanks,
Jacob

**Comment by CodeReclaimers** [comment]
Ah, I see what's happening, the version on PyPI doesn't have the examples packaged with it, so when you install via pip you just get the actual library.  (I think I'll change that in the next release.)

You can get the most recent code from GitHub by cloning (`git clone https://github.com/CodeReclaimers/neat-python.git`) or by just downloading the current archive (https://github.com/CodeReclaimers/neat-python/archive/master.zip).

To install from the source, I would first do an uninstall with pip, and then from the top directory, where setup.py is located, run `python setup.py install` (I can't recall whether you need to do this as administrator on Windows or not).  Let me know if you run into any troubles with that. :)

**Comment by duijnhouwer** [comment]
Hi,

I tried some other things to get your NEAT-python to run

I installed the library (version 0.6) using pip install neat-python
and then tried to run the examples that i cloned from your GitHub
repository.

I tried to run the xor2.py example.

First, off. I noticed that it is written in Python-2. I changed the print
functions and removed the dependency of cPickle, to see how far i'd get.

Not far, on the next line, " from neat import chromosome " doesn't work

ImportError: cannot import name 'chromosome'


The next line,

from neat.nn import nn_pure as nn

also doesn't work

ImportError: cannot import name 'nn_pure'



Any suggestions?



On Wed, Jan 27, 2016 at 11:10 PM, Jacob Duijnhouwer <j.duijnhouwer@gmail.com
> wrote:

> is neat-python compatible with Python-3?
>
> On Wed, Jan 27, 2016 at 11:09 PM, Jacob Duijnhouwer <

**Comment by CodeReclaimers** [comment]
Apologies for the delay--I've been overwhelmed with other stuff for the last few days, and all my NEAT-related stuff fell through the cracks.

The examples from the Git repository won't work with the library installed from PyPI through pip, because things are still changing pretty rapidly.  But what you can do is download the release snapshot of the repository for version 0.6 here: https://github.com/CodeReclaimers/neat-python/releases/tag/v0.6

That should have examples that will work with the PyPI version.  Hopefully I can get things cleaned up enough for another release soon, and I'll include the examples along with that release, so that this isn't a problem going forward.

**Comment by CodeReclaimers** [comment]
The ReadTheDocs page now shows the config file, and also warns about getting the example source to match the PyPI library.
