### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by arthurpaulino** [CodeReclaimers/neat-python#135]
How do I cite your work?

[Example](https://github.com/openai/gym#openai-gym)

**Comment by CodeReclaimers** [comment]
I've added a Bibtex entry to the README that credits the project maintainers all the way back to the original implementation.  Please let me know if it needs to be tweaked--it's been a while since I wrote a paper. :)

Also: if any of the project contributors would like their name listed, please let me know.  Thanks again to everybody that has contributed!

**Comment by arthurpaulino** [comment]
Thank you very much!
