### ISSUE TITLE
Not returning best genome

### ISSUE THREAD

**Issue by Sloth6** [CodeReclaimers/neat-python#16]
Currently, pop.most_fit_genomes[-1] is the best genome from the last generation. Unless I'm missing something this is undesirable and often the best genome ever may have stagnated earlier and won't be returned. 

I have fixed this with another variable storing the best ever but one could also store the fitness along with each one in "most_fit_genomes" , and then return the max of all those sorted.

Joel

**Comment by CodeReclaimers** [comment]
Thanks, this has bugged me too but I just hadn't taken the time to add it yet.  I've got some pending refactoring and other changes, and I'll make sure to include a "most fit ever" member amongst the statistics, or at least a convenience method for retrieving the most N fit genomes ever seen.  

Just so you know, the genomes in most_fit_genomes do actually have a `fitness` member, so you could sort them based on that and take the end element(s).  The genomes in most_fit_genomes are deep copies of those in the population, so if the most fit genome gets rolled over into the next generation because of elitism, and assigned a different score in a later generation for some reason, the copy in most_fit_genomes will still have the original score for each genome as it was in the original generation.

**Comment by Sloth6** [comment]
ok, here is what i'm using if anyone else wants to add it (to population.py). I would open a pull request but I have a bunch of other very custom changes. 

    def best_genomes(self, n):
        key = lambda g: g.fitness
        return sorted(self.most_fit_genomes, key=key, reverse=True )[:n]

    def best_genome(self):
        return self.best_genomes(1)[0]

**Comment by CodeReclaimers** [comment]
Thanks! I'll make sure that gets into the next release.

**Comment by Sloth6** [comment]
I realized a major flaw in the code I posted. Due to cloning, identical genomes appear in the top list, thus best_genomes(n) can return n identical copies. The following fixes this by assuring each of the top n is from a different lineage. 

    def best_genomes(self, n):
        top_n = []
        used_ids = set()
        key = lambda g: g.fitness
        sorted_genomes = sorted(self.most_fit_genomes, key=key, reverse=True )
        
        i = 0
        while( i < len(sorted_genomes) and len(top_n) < n ):
            genome = sorted_genomes[i]
            if genome.ID not in used_ids:
                top_n.append(genome)
                used_ids.add(genome.ID)
            i += 1
            
        return top_n

**Comment by CodeReclaimers** [comment]
Thanks, I'll make that change as well!

**Comment by CodeReclaimers** [comment]
This capability is now present in the StatisticsReporter class, an instance of which is created as the statistics member of a Population object.
