### ISSUE TITLE
NEAT with multiple outputs

### ISSUE THREAD

**Issue by pabloxrl** [CodeReclaimers/neat-python#28]
Hi

I see that in the example with xor it is very straightforward to map a couple of inputs to one outputs.

Is it possible to have a scenario with multiple outputs and inputs? If so, how to set the config file?

Let's imagine a rock-paper-scissors example where rock=0, paper = 1, scissors=2

rps_inputs = [[0, 0], [0, 1], [1, 1], [0, 2], [1, 2], [2, 2]]
rps_outputs = [0, 1, 1, 0, 2, 2]

Would that be enough to modify the config file to have three inputs and three outputs?

Cheers

**Comment by CodeReclaimers** [comment]
For a three-state output like that, you might want to look at using rock=-1, paper=0, scissors=1, and then change the `activation_functions` setting (in the phenotype section of the config file) from sigmoid to tanh (because tanh outputs go from -1 to 1, while sigmoid is only 0 to 1). 

Alternatively, you could add `identity` to the list of allowed activation functions, and then the network would be free to evolve outputs that are not limited to a particular output range.

However, if I understand correctly, what people will frequently do when they want three or more possible output values from a neural net is create a single bit for each possible output.  So in your case you might have three outputs, and your rps_outputs values would be something like [[1, 0, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [0, 0, 1], [0, 0, 1]].  If you go that route. you would just need to change the `output_nodes` setting in the config file from 1 to 3.

**Comment by CodeReclaimers** [comment]
TODO: Add an example like this somewhere

**Comment by CodeReclaimers** [comment]
In the OpenAI Gym example for the lander (https://github.com/CodeReclaimers/neat-python/tree/master/examples/openai-lander), the simulator has 4 exclusive actions, encoded as an integer: 0=do nothing, 1=left thruster, 2=right thruster, 3=main thruster.  To handle this, I use only 'clamped' nodes in the network, so that the outputs are all on the range [-1, 1].  This is meant to be an estimate of the discounted reward that is to be expected from each action, so we take the index of the output with the largest value to be the best action, because the intent is to accumulate a large positive reward.

If you're using NumPy, getting the index of the largest value is conveniently done using the argmax function: action = np.argmax(net.activate(observation))
