### ISSUE TITLE
population.py: invalid conversion specification

### ISSUE THREAD

**Issue by mstechly** [CodeReclaimers/neat-python#3]
I tried running xor2.py, and got:
ValueError: Invalid conversion specification
from line 248 in population.py:

    print('Best fitness: {0:2.12!s} - size: {1!s} - species {2!s} - id {3!s}'.format(best.fitness, best.size(), best.species_id, best.ID))
I changed it to:

    print('Best fitness: {0:2.12f} - size: {1} - species {2} - id {3}'.format(best.fitness, best.size(), best.species_id, best.ID))
and it's working now, however I'm not sure if with intended formatting, since I'm not familiar with format().

**Comment by CodeReclaimers** [comment]
Thanks, this should be taken care of in 0995ae97139f33f440808147e200e71f35382468, but it wouldn't surprise me if there are some other lurking cases which I can't spot right now because I don't know the format() specifiers very well.  

I honestly still prefer the % operator, but that appears to be "old fashioned" now. :P
