### ISSUE TITLE
"def f(values)" printed

### ISSUE THREAD

**Issue by mstechly** [CodeReclaimers/neat-python#4]
In xor2.py, at the end I get:

    def f(values):
        # evaluate layer 0
        z = (-1.228525 * values[1]) + (2.027144 * values[0])
        values[3] = exp_sigmoid(0.000000, 2.759253, z)

        # evaluate layer 1
        z = (-4.078686 * values[1]) + (1.482555 * values[0]) + (-0.602657 * values[3])
        values[4] = exp_sigmoid(0.000000, 22.485587, z)

        # evaluate layer 2
        z = (0.501858 * values[3]) + (-0.821980 * values[4])
        values[2] = exp_sigmoid(1.911005, -21.703904, z)

This is probably created by create_feed_forward_function in neat/nn/__init__.py, but I didn't trace where it's printed out.
This doesn't concern xor2_spiking.py or xor2_parallel.py.

I also get a single number at the end of the execution of all xor examples, without any indication about its meaning. It seems to be total number of generations.

**Comment by mstechly** [comment]
Ok, it's printed out in xor2.py, line 39.
However, I still don't really see the point of printing it out.

**Comment by CodeReclaimers** [comment]
Thanks for mentioning these! I had meant to remove the function printout, because it just clutters up the XOR example.  The generation count printout is probably some debugging code left there from the original project, and should be removed too.  I've taken care of both of these in my local copy, so the next time I commit they should be gone.
