### ISSUE TITLE
What is new "species_elitism" parameter ?

### ISSUE THREAD

**Issue by d0pa** [CodeReclaimers/neat-python#50]
There is no information in documentation about "species_elitism", what does it do ?

**Comment by CodeReclaimers** [comment]
Sorry about that--if you set species_elitism to an integer N, it blocks marking the last N species as stagnant.  Setting it to 0 will make neat-python act like it did before this parameter was added.

This is mainly to avoid the hassle of having all species go extinct just because they all happened to go extinct at nearly the same time.

**Comment by CodeReclaimers** [comment]
Added to documentation in commit 2e17c8983295c495f51a441838981248a2bced53.
