### ISSUE TITLE
max_fitness_threshold = extinction

### ISSUE THREAD

**Issue by cafawo** [CodeReclaimers/neat-python#67]
If the maximum fitness threshold is unknown, would it be possible(/useful) to simply extract the best genome after extinction?

Currently, NEAT throws a CompleteExtinctionException without saving results. Which is OK because this might simply be due to a bad problem set-up. But maybe the proposed modification could be part of the max_fitness_threshold or reset_on_extinction options.

Thanks once more for your help and this great project.

**Comment by d0pa** [comment]
It looks like, you can use last checkpoint for getting best genome after extinction.

**Comment by CodeReclaimers** [comment]
If you gave the Population a stats reporter, you can catch the CompleteExtinctionException and then query the stats object for the best genome(s).  This is something I should document somewhere, so that at least there's a clear indication of how to handle this situation with the current implementation.

I sometimes find myself using a very large value for max fitness (like 1e38) in cases where I want to control how many generations I want to run.  There's an example of this in the OpenAI lander example (https://github.com/CodeReclaimers/neat-python/blob/master/examples/openai-lander/evolve.py).  Because the maximum score this environment will give is (I think) 300, I set the fitness threshold to 1000 and then just run 1 generation at a time, and break out of that loop if I get a solution that's good enough.

**Comment by mdalvi** [comment]
I guess this issue **should be marked as fixed**, since v0.92 now has `no_fitness_termination` parameter under [[NEAT] section](http://neat-python.readthedocs.io/en/latest/config_file.html#neat-section) configurations which relaxes the `fitness_criterion `and `fitness_threshold`
